parameters: {}
environment: {}
packages:
  - name: bluesky-covid-wastewater
    shared: false
    environment: {}
    parameters: {}
    annotations: {}
    functions:
      - name: post
        binary: false
        main: ""
        runtime: nodejs:18
        web: true
        webSecure: false
        parameters: {}
        environment:
          { BSKY_ID: "${BSKY_ID}", BSKY_PASSWORD: "${BSKY_PASSWORD}" }
        annotations: {}
        limits: { memory: 512 }
        triggers:
          - name: tues-test
            sourceType: scheduler
            sourceDetails:
              cron: "40 11 * * 1"
          - name: every-saturday
            sourceType: scheduler
            sourceDetails:
              cron: "0 16 * * 6"
          - name: every-monday
            sourceType: scheduler
            sourceDetails:
              cron: "0 6 * * 1"
