parameters: {}
environment: {}
packages:
  - name: bluesky-covid-wastewater
    shared: false
    environment: {}
    parameters: {}
    annotations: {}
    functions:
      - name: post
        binary: false
        main: ""
        runtime: nodejs:18
        web: true
        webSecure: false
        parameters: {}
        environment: { BSKY_ID: "${BSKY_ID}", BSKY_PASSWORD: "${BSKY_PASSWORD}", BLOCK_REPLIES: "${BLOCK_REPLIES}", MAX_ATTEMPTS: "${MAX_ATTEMPTS}", PAUSE_BETWEEN_ATTEMPTS: "${PAUSE_BETWEEN_ATTEMPTS}" }
        annotations: {}
        limits: { memory: 512 }
        triggers:
          - name: every-friday
            sourceType: scheduler
            sourceDetails:
              cron: "1 11 * * 5"
